# Generated by Django 5.0.11 on 2025-01-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notablehuman',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notablehuman',
            name='wikipedia_url',
            field=models.URLField(blank=True, default=None, max_length=500),
            preserve_default=False,
        ),
    ]
