# Generated by Django 5.0.11 on 2025-01-28 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_alter_notablehuman_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notablehuman',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.AddField(
            model_name='gender',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='place',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
