# Generated by Django 5.0.11 on 2025-01-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0003_rename_updated_at_notablehuman_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
