# Generated by Django 5.0.11 on 2025-01-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0004_tasklock'),
    ]

    operations = [
        migrations.AddField(
            model_name='notablehuman',
            name='is_birth_bc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notablehuman',
            name='is_death_bc',
            field=models.BooleanField(default=False),
        ),
    ]
