# Generated by Django 5.0.11 on 2025-01-31 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0005_notablehuman_is_birth_bc_notablehuman_is_death_bc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskLock',
        ),
    ]
