# Generated by Django 5.0.11 on 2025-02-02 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0006_delete_tasklock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notablehuman',
            name='gender',
        ),
        migrations.CreateModel(
            name='NotableHumanAttribute',
            fields=[
                ('wikidata_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('gender', 'Gender'), ('occupation', 'Occupation'), ('ethnic_group', 'Ethnic Group'), ('field_of_work', 'Field of Work')], max_length=50)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('label', 'category')},
            },
        ),
        migrations.AddField(
            model_name='notablehuman',
            name='attributes',
            field=models.ManyToManyField(related_name='notable_humans', to='data_collection.notablehumanattribute'),
        ),
    ]
