# Generated by Django 5.0.11 on 2025-02-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0007_remove_notablehuman_gender_notablehumanattribute_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
