# Generated by Django 5.0.11 on 2025-02-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0008_delete_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notablehumanattribute',
            name='category',
            field=models.CharField(choices=[('gender', 'Gender'), ('occupation', 'Occupation'), ('ethnic_group', 'Ethnic Group'), ('field_of_work', 'Field of Work'), ('member_of', 'Member Of')], max_length=50),
        ),
    ]
