# Generated by Django 5.0.11 on 2025-02-08 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0012_alter_notablehumanattribute_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notablehuman',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='notablehuman',
            name='last_wikidata_update',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 10, 54, 43, 717734, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notablehuman',
            name='last_wikipedia_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
