# Generated by Django 5.0.11 on 2025-02-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0014_notablehuman_article_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notablehuman',
            old_name='article_creation_date',
            new_name='article_created_date',
        ),
        migrations.AlterField(
            model_name='notablehuman',
            name='article_quality',
            field=models.CharField(choices=[('good', 'Good Article'), ('featured', 'Featured Article')], default=None, max_length=10),
        ),
    ]
