# Generated by Django 5.0.11 on 2025-02-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0015_rename_article_creation_date_notablehuman_article_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notablehuman',
            name='article_quality',
            field=models.CharField(choices=[('unrated', 'Unrated Article'), ('good', 'Good Article'), ('featured', 'Featured Article')], default='unrated', max_length=10),
        ),
    ]
