# Generated by Django 5.0.11 on 2025-02-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0016_alter_notablehuman_article_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='notablehuman',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
