# Generated by Django 5.0.11 on 2025-02-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0017_notablehuman_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notablehumanattribute',
            unique_together=set(),
        ),
    ]
