# Generated by Django 5.0.11 on 2025-02-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0019_alter_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notablehuman',
            name='birth_year',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='notablehuman',
            name='death_year',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
